version: "3"
services:
  eshop-image:
    image: eshop-image
    ports:
      - "8080:8080"
    networks:
      - eshop-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - eshop-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eshop

networks:
  eshop-mysql: